### ISSUE TITLE
Travel: Starport has permanently landed shuttle.

### ISSUE THREAD

**Issue by Tenkata** [kinshi/tarkin_scripts#95]
Category:  Travel
Reproducibility: Always
Severity: Minor
Priority: Low
Summary: A shuttle appears to be permanently landed at every Starport. The functional shuttle operates normally.
Description: A shuttle seems to have been put in place at each starport that is independent of the shuttle associated with the Travel system. This shuttle does nothing and does not impact a player's ability to travel but may cause confusion as to the current status of the functioning shuttle.
Steps To Reproduce: N/A 
Attached Files:  
![screenshot0011](https://cloud.githubusercontent.com/assets/1145639/7664190/2f050d56-fb31-11e4-8bbc-578796ba7519.jpg)

**Comment by kinshi** [comment]
Know issue and was a mentioned as a "Not a bug" on the forum thread for testables

http://forums.tarkin.org/index.php?/topic/3906-things-to-look-for-on-thrawn/

"Note: You may witness double-spawns of some shuttle, this is known and is not a bug (it is a solution for an issue that applies to Tarkin only, so this will only appear that way on Thrawn."

This is because a bug from SWGEmu last year caused all the hidden shuttle spawners to fail to spawn in game and otherwise not function, and to make NPC shuttles work again, I had to remove all the original shuttle spawners, and replaced them using screenplays for each city to spawn new shuttles.

This situation only occurs on Tarkin, and is expected on Thrawn since its original shuttle spawners are still present but the added shuttle spawn screenplays are also active,

**Comment by Thrax989** [comment]
Why not just set your shuttle time from leaving to 86400 that way your shuttles never leave the ground always allowing your players access to fly from and to a planet all day long and not have to wait around to see these bugs..

**Comment by Tenkata** [comment]
To respond to your question, to work around a problem is not actually fixing the problem itself. It will only avoid it. The intent of Thrawn is so that people can go onto the server and test things out and help Kinshi find bugs so that they can be fixed.

To implement your solution would be to completely defeat the purpose of the instant travel system.

**Comment by kinshi** [comment]
We have abandoned the default NPC travel system and have replaced it with a different system, as such any changes to the old travel system would be moot.

**Comment by kinshi** [comment]
as such, not a bug
